name: Send RBI News Email

on:
  schedule:
    - cron: '0 8 * * *' # Runs every day at 8:00 AM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Create credentials.json
      run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

    - name: Set environment variables
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: echo "Environment variables set"

    - name: Run Python script
      run: python send_rbi_news.py
