name: Send RBI News Email

on:
  schedule:
    - cron: '30 17 * * *'  # Runs every day at 17:30 UTC (11:00 PM IST)
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      # Remaining workflow steps...
